export './home/home_screen.dart';
export './loading/loading_screen.dart';
export './home/taller_servicio_screen.dart';
export './placa/ingresar_placa_screen.dart';
export './ruc/ingresar_ruc_screen.dart';
export './turnos/turno_asignado_screen.dart';
export './config/config_screen.dart';
export './turnos/turnero_waiting_screen.dart';
export './kiosco/tipo_atencion_screen.dart';